stock_analysis:
  outputs:
    dev:
      account: DICTEOE-GH21479
      database: STOCKS_DB
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: STOCK_ANALYST
      schema: STOCKS
      threads: 1
      type: snowflake
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      warehouse: STOCK_WH
  target: dev
